# Generated by Django 4.2.27 on 2025-12-14 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source_url', models.URLField(help_text='Original repository URL (e.g., GitHub, GitLab)')),
                ('source_type', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('gitea', 'Gitea'), ('custom', 'Custom Git Server')], default='github', max_length=50)),
                ('local_path', models.CharField(help_text='Local file system path', max_length=512, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('initializing', 'Initializing'), ('mirroring', 'Mirroring'), ('active', 'Active'), ('failed', 'Failed'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('is_mirror', models.BooleanField(default=True)),
                ('is_bare', models.BooleanField(default=True)),
                ('default_branch', models.CharField(blank=True, default='main', max_length=255)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_commit_hash', models.CharField(blank=True, max_length=40)),
                ('total_commits', models.IntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, help_text='Error details if status is failed')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='accounts.organisation')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_repositories', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GitCommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_hash', models.CharField(db_index=True, max_length=40)),
                ('author_name', models.CharField(max_length=255)),
                ('author_email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('committed_at', models.DateTimeField()),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='repositories.gitrepository')),
            ],
            options={
                'ordering': ['-committed_at'],
            },
        ),
        migrations.CreateModel(
            name='GitBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('commit_hash', models.CharField(max_length=40)),
                ('is_default', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='repositories.gitrepository')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SyncTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('commits_synced', models.IntegerField(default=0)),
                ('task_id', models.CharField(blank=True, help_text='Celery task ID', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_tasks', to='repositories.gitrepository')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['repository', 'status'], name='git_synctas_reposit_355ddd_idx'), models.Index(fields=['status'], name='git_synctas_status_4745a0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='gitrepository',
            index=models.Index(fields=['organisation', 'status'], name='git_gitrepo_organis_1aca7a_idx'),
        ),
        migrations.AddIndex(
            model_name='gitrepository',
            index=models.Index(fields=['source_url'], name='git_gitrepo_source__1c48d3_idx'),
        ),
        migrations.AddIndex(
            model_name='gitrepository',
            index=models.Index(fields=['status'], name='git_gitrepo_status_27887c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gitrepository',
            unique_together={('organisation', 'name')},
        ),
        migrations.AddIndex(
            model_name='gitcommit',
            index=models.Index(fields=['repository', 'committed_at'], name='git_gitcomm_reposit_689ec2_idx'),
        ),
        migrations.AddIndex(
            model_name='gitcommit',
            index=models.Index(fields=['author_email'], name='git_gitcomm_author__b9bbfd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gitcommit',
            unique_together={('repository', 'commit_hash')},
        ),
        migrations.AddIndex(
            model_name='gitbranch',
            index=models.Index(fields=['repository', 'is_default'], name='git_gitbran_reposit_509e79_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gitbranch',
            unique_together={('repository', 'name')},
        ),
    ]
