# Generated by Django 4.2.27 on 2025-12-19 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gitbranch',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='gitbranch',
            name='repository',
        ),
        migrations.AlterUniqueTogether(
            name='gitcommit',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='gitcommit',
            name='repository',
        ),
        migrations.RemoveIndex(
            model_name='gitrepository',
            name='repos_gitrepo_org_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='gitrepository',
            name='repos_gitrepo_source_url_idx',
        ),
        migrations.RemoveIndex(
            model_name='gitrepository',
            name='repos_gitrepo_status_idx',
        ),
        migrations.RenameIndex(
            model_name='synctask',
            new_name='repositorie_reposit_65e94b_idx',
            old_name='repos_synctask_repo_status_idx',
        ),
        migrations.RenameIndex(
            model_name='synctask',
            new_name='repositorie_status_dca7ee_idx',
            old_name='repos_synctask_status_idx',
        ),
        migrations.RemoveField(
            model_name='gitrepository',
            name='default_branch',
        ),
        migrations.RemoveField(
            model_name='gitrepository',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='gitrepository',
            name='is_mirror',
        ),
        migrations.RemoveField(
            model_name='gitrepository',
            name='last_commit_hash',
        ),
        migrations.RemoveField(
            model_name='gitrepository',
            name='last_synced_at',
        ),
        migrations.RemoveField(
            model_name='gitrepository',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='gitrepository',
            name='source_url',
        ),
        migrations.RemoveField(
            model_name='gitrepository',
            name='status',
        ),
        migrations.RemoveField(
            model_name='gitrepository',
            name='total_commits',
        ),
        migrations.AlterField(
            model_name='gitrepository',
            name='is_bare',
            field=models.BooleanField(default=True, help_text='Whether this is a bare repository (no working directory)'),
        ),
        migrations.AlterField(
            model_name='gitrepository',
            name='local_path',
            field=models.CharField(help_text='Local file system path where the repository is stored', max_length=512, unique=True),
        ),
        migrations.AddIndex(
            model_name='gitrepository',
            index=models.Index(fields=['organisation', 'name'], name='repositorie_organis_8d14cb_idx'),
        ),
        migrations.CreateModel(
            name='GitMirrorRepository',
            fields=[
                ('gitrepository_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='repositories.gitrepository')),
                ('source_url', models.URLField(help_text='Original repository URL (e.g., GitHub, GitLab)')),
                ('source_type', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('gitea', 'Gitea'), ('bitbucket', 'Bitbucket'), ('custom', 'Custom Git Server')], default='github', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('initializing', 'Initializing'), ('active', 'Active'), ('failed', 'Failed'), ('paused', 'Paused')], default='pending', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_interval', models.IntegerField(default=3600, help_text='Sync interval in seconds (default: 1 hour)')),
                ('auto_sync', models.BooleanField(default=True, help_text='Automatically sync this mirror on schedule')),
                ('error_message', models.TextField(blank=True, help_text='Error details if status is failed')),
                ('consecutive_failures', models.IntegerField(default=0, help_text='Number of consecutive sync failures')),
            ],
            bases=('repositories.gitrepository',),
        ),
        migrations.DeleteModel(
            name='GitBranch',
        ),
        migrations.DeleteModel(
            name='GitCommit',
        ),
        migrations.AddIndex(
            model_name='gitmirrorrepository',
            index=models.Index(fields=['status'], name='repositorie_status_1ae205_idx'),
        ),
        migrations.AddIndex(
            model_name='gitmirrorrepository',
            index=models.Index(fields=['source_url'], name='repositorie_source__169a54_idx'),
        ),
        migrations.AddIndex(
            model_name='gitmirrorrepository',
            index=models.Index(fields=['auto_sync', 'last_synced_at'], name='repositorie_auto_sy_2996b3_idx'),
        ),
    ]
