# Generated by Django 4.2.27 on 2025-12-20 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_team_alter_organisationinvite_role_and_more'),
        ('repositories', '0002_alter_gitbranch_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryAccessPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('none', 'None'), ('read', 'Read'), ('write', 'Write'), ('admin', 'Admin')], help_text='Organisation membership role this policy applies to', max_length=20, null=True)),
                ('permission', models.CharField(choices=[('none', 'None'), ('read', 'Read'), ('write', 'Write'), ('admin', 'Admin')], default='none', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_policies', to='repositories.gitrepository')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repository_policies', to='accounts.team')),
            ],
            options={
                'ordering': ['repository', 'team', 'role'],
                'indexes': [models.Index(fields=['repository', 'team'], name='repositorie_reposit_8f5a98_idx'), models.Index(fields=['repository', 'role'], name='repositorie_reposit_b93a2b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='repositoryaccesspolicy',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('team__isnull', False), ('role__isnull', True)), models.Q(('team__isnull', True), ('role__isnull', False)), _connector='OR'), name='repository_policy_exactly_one_subject'),
        ),
        migrations.AlterUniqueTogether(
            name='repositoryaccesspolicy',
            unique_together={('repository', 'role'), ('repository', 'team')},
        ),
    ]
