# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from accounts.grpc import accounts_pb2 as accounts_dot_grpc_dot_accounts__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in accounts/grpc/accounts_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CurrentUserControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCurrentUser = channel.unary_unary(
                '/config.accounts.CurrentUserController/GetCurrentUser',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=accounts_dot_grpc_dot_accounts__pb2.UserResponse.FromString,
                _registered_method=True)
        self.UpdateCurrentUser = channel.unary_unary(
                '/config.accounts.CurrentUserController/UpdateCurrentUser',
                request_serializer=accounts_dot_grpc_dot_accounts__pb2.CurrentUserUpdateCurrentUserRequest.SerializeToString,
                response_deserializer=accounts_dot_grpc_dot_accounts__pb2.UserResponse.FromString,
                _registered_method=True)


class CurrentUserControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCurrentUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCurrentUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CurrentUserControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCurrentUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentUser,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=accounts_dot_grpc_dot_accounts__pb2.UserResponse.SerializeToString,
            ),
            'UpdateCurrentUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCurrentUser,
                    request_deserializer=accounts_dot_grpc_dot_accounts__pb2.CurrentUserUpdateCurrentUserRequest.FromString,
                    response_serializer=accounts_dot_grpc_dot_accounts__pb2.UserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'config.accounts.CurrentUserController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('config.accounts.CurrentUserController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CurrentUserController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCurrentUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.accounts.CurrentUserController/GetCurrentUser',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            accounts_dot_grpc_dot_accounts__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCurrentUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.accounts.CurrentUserController/UpdateCurrentUser',
            accounts_dot_grpc_dot_accounts__pb2.CurrentUserUpdateCurrentUserRequest.SerializeToString,
            accounts_dot_grpc_dot_accounts__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CurrentUserProfileControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCurrentUserProfile = channel.unary_unary(
                '/config.accounts.CurrentUserProfileController/GetCurrentUserProfile',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=accounts_dot_grpc_dot_accounts__pb2.UserProfileResponse.FromString,
                _registered_method=True)
        self.UpdateCurrentUserProfile = channel.unary_unary(
                '/config.accounts.CurrentUserProfileController/UpdateCurrentUserProfile',
                request_serializer=accounts_dot_grpc_dot_accounts__pb2.CurrentUserProfileUpdateCurrentUserProfileRequest.SerializeToString,
                response_deserializer=accounts_dot_grpc_dot_accounts__pb2.UserProfileResponse.FromString,
                _registered_method=True)


class CurrentUserProfileControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCurrentUserProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCurrentUserProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CurrentUserProfileControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCurrentUserProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentUserProfile,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=accounts_dot_grpc_dot_accounts__pb2.UserProfileResponse.SerializeToString,
            ),
            'UpdateCurrentUserProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCurrentUserProfile,
                    request_deserializer=accounts_dot_grpc_dot_accounts__pb2.CurrentUserProfileUpdateCurrentUserProfileRequest.FromString,
                    response_serializer=accounts_dot_grpc_dot_accounts__pb2.UserProfileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'config.accounts.CurrentUserProfileController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('config.accounts.CurrentUserProfileController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CurrentUserProfileController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCurrentUserProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.accounts.CurrentUserProfileController/GetCurrentUserProfile',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            accounts_dot_grpc_dot_accounts__pb2.UserProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCurrentUserProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.accounts.CurrentUserProfileController/UpdateCurrentUserProfile',
            accounts_dot_grpc_dot_accounts__pb2.CurrentUserProfileUpdateCurrentUserProfileRequest.SerializeToString,
            accounts_dot_grpc_dot_accounts__pb2.UserProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
