# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: accounts/grpc/accounts.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'accounts/grpc/accounts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x61\x63\x63ounts/grpc/accounts.proto\x12\x0f\x63onfig.accounts\x1a\x1bgoogle/protobuf/empty.proto\"T\n1CurrentUserProfileUpdateCurrentUserProfileRequest\x12\x0b\n\x03\x62io\x18\x01 \x01(\t\x12\x12\n\navatar_url\x18\x02 \x01(\t\"[\n#CurrentUserUpdateCurrentUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\"\xd0\x01\n\x13UserProfileResponse\x12\x0f\n\x02id\x18\x01 \x01(\x03H\x00\x88\x01\x01\x12\x30\n\x04user\x18\x02 \x01(\x0b\x32\x1d.config.accounts.UserResponseH\x01\x88\x01\x01\x12\x10\n\x03\x62io\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x17\n\navatar_url\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x16\n\tis_active\x18\x05 \x01(\x08H\x04\x88\x01\x01\x42\x05\n\x03_idB\x07\n\x05_userB\x06\n\x04_bioB\r\n\x0b_avatar_urlB\x0c\n\n_is_active\"\xa4\x01\n\x0cUserResponse\x12\x0f\n\x02id\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x12\n\x05\x65mail\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x17\n\nfirst_name\x18\x04 \x01(\tH\x02\x88\x01\x01\x12\x16\n\tlast_name\x18\x05 \x01(\tH\x03\x88\x01\x01\x42\x05\n\x03_idB\x08\n\x06_emailB\r\n\x0b_first_nameB\x0c\n\n_last_name2\xce\x01\n\x15\x43urrentUserController\x12I\n\x0eGetCurrentUser\x12\x16.google.protobuf.Empty\x1a\x1d.config.accounts.UserResponse\"\x00\x12j\n\x11UpdateCurrentUser\x12\x34.config.accounts.CurrentUserUpdateCurrentUserRequest\x1a\x1d.config.accounts.UserResponse\"\x00\x32\x80\x02\n\x1c\x43urrentUserProfileController\x12W\n\x15GetCurrentUserProfile\x12\x16.google.protobuf.Empty\x1a$.config.accounts.UserProfileResponse\"\x00\x12\x86\x01\n\x18UpdateCurrentUserProfile\x12\x42.config.accounts.CurrentUserProfileUpdateCurrentUserProfileRequest\x1a$.config.accounts.UserProfileResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'accounts.grpc.accounts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CURRENTUSERPROFILEUPDATECURRENTUSERPROFILEREQUEST']._serialized_start=78
  _globals['_CURRENTUSERPROFILEUPDATECURRENTUSERPROFILEREQUEST']._serialized_end=162
  _globals['_CURRENTUSERUPDATECURRENTUSERREQUEST']._serialized_start=164
  _globals['_CURRENTUSERUPDATECURRENTUSERREQUEST']._serialized_end=255
  _globals['_USERPROFILERESPONSE']._serialized_start=258
  _globals['_USERPROFILERESPONSE']._serialized_end=466
  _globals['_USERRESPONSE']._serialized_start=469
  _globals['_USERRESPONSE']._serialized_end=633
  _globals['_CURRENTUSERCONTROLLER']._serialized_start=636
  _globals['_CURRENTUSERCONTROLLER']._serialized_end=842
  _globals['_CURRENTUSERPROFILECONTROLLER']._serialized_start=845
  _globals['_CURRENTUSERPROFILECONTROLLER']._serialized_end=1101
# @@protoc_insertion_point(module_scope)
