# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from documents.grpc import documents_pb2 as documents_dot_grpc_dot_documents__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in documents/grpc/documents_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DocumentReadControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
                '/config.documents.DocumentReadController/List',
                request_serializer=documents_dot_grpc_dot_documents__pb2.DocumentListRequest.SerializeToString,
                response_deserializer=documents_dot_grpc_dot_documents__pb2.DocumentListResponse.FromString,
                _registered_method=True)
        self.Retrieve = channel.unary_unary(
                '/config.documents.DocumentReadController/Retrieve',
                request_serializer=documents_dot_grpc_dot_documents__pb2.DocumentRetrieveRequest.SerializeToString,
                response_deserializer=documents_dot_grpc_dot_documents__pb2.DocumentResponse.FromString,
                _registered_method=True)
        self.StreamPages = channel.unary_stream(
                '/config.documents.DocumentReadController/StreamPages',
                request_serializer=documents_dot_grpc_dot_documents__pb2.DocumentReadStreamPagesRequest.SerializeToString,
                response_deserializer=documents_dot_grpc_dot_documents__pb2.PageResponse.FromString,
                _registered_method=True)


class DocumentReadControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocumentReadControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=documents_dot_grpc_dot_documents__pb2.DocumentListRequest.FromString,
                    response_serializer=documents_dot_grpc_dot_documents__pb2.DocumentListResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=documents_dot_grpc_dot_documents__pb2.DocumentRetrieveRequest.FromString,
                    response_serializer=documents_dot_grpc_dot_documents__pb2.DocumentResponse.SerializeToString,
            ),
            'StreamPages': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamPages,
                    request_deserializer=documents_dot_grpc_dot_documents__pb2.DocumentReadStreamPagesRequest.FromString,
                    response_serializer=documents_dot_grpc_dot_documents__pb2.PageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'config.documents.DocumentReadController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('config.documents.DocumentReadController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DocumentReadController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.documents.DocumentReadController/List',
            documents_dot_grpc_dot_documents__pb2.DocumentListRequest.SerializeToString,
            documents_dot_grpc_dot_documents__pb2.DocumentListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.documents.DocumentReadController/Retrieve',
            documents_dot_grpc_dot_documents__pb2.DocumentRetrieveRequest.SerializeToString,
            documents_dot_grpc_dot_documents__pb2.DocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamPages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/config.documents.DocumentReadController/StreamPages',
            documents_dot_grpc_dot_documents__pb2.DocumentReadStreamPagesRequest.SerializeToString,
            documents_dot_grpc_dot_documents__pb2.PageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
