# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from repositories.grpc import repositories_pb2 as repositories_dot_grpc_dot_repositories__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in repositories/grpc/repositories_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GitMirrorRepositoryAdminControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/config.repositories.GitMirrorRepositoryAdminController/Create',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryResponse.FromString,
                _registered_method=True)
        self.Destroy = channel.unary_unary(
                '/config.repositories.GitMirrorRepositoryAdminController/Destroy',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryDestroyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/config.repositories.GitMirrorRepositoryAdminController/List',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryListRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryListResponse.FromString,
                _registered_method=True)
        self.PartialUpdate = channel.unary_unary(
                '/config.repositories.GitMirrorRepositoryAdminController/PartialUpdate',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryPartialUpdateRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryResponse.FromString,
                _registered_method=True)
        self.Retrieve = channel.unary_unary(
                '/config.repositories.GitMirrorRepositoryAdminController/Retrieve',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryRetrieveRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/config.repositories.GitMirrorRepositoryAdminController/Update',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryResponse.FromString,
                _registered_method=True)


class GitMirrorRepositoryAdminControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PartialUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GitMirrorRepositoryAdminControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryResponse.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryDestroyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryListRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryListResponse.SerializeToString,
            ),
            'PartialUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.PartialUpdate,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryPartialUpdateRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryRetrieveRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'config.repositories.GitMirrorRepositoryAdminController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('config.repositories.GitMirrorRepositoryAdminController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GitMirrorRepositoryAdminController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.GitMirrorRepositoryAdminController/Create',
            repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.GitMirrorRepositoryAdminController/Destroy',
            repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryDestroyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.GitMirrorRepositoryAdminController/List',
            repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryListRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PartialUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.GitMirrorRepositoryAdminController/PartialUpdate',
            repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryPartialUpdateRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.GitMirrorRepositoryAdminController/Retrieve',
            repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryRetrieveRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.GitMirrorRepositoryAdminController/Update',
            repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class GitMirrorRepositoryMirroringControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateMirror = channel.unary_unary(
                '/config.repositories.GitMirrorRepositoryMirroringController/CreateMirror',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryMirroringCreateMirrorRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryMirroringCreateMirrorResponse.FromString,
                _registered_method=True)


class GitMirrorRepositoryMirroringControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateMirror(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GitMirrorRepositoryMirroringControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateMirror': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMirror,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryMirroringCreateMirrorRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryMirroringCreateMirrorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'config.repositories.GitMirrorRepositoryMirroringController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('config.repositories.GitMirrorRepositoryMirroringController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GitMirrorRepositoryMirroringController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateMirror(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.GitMirrorRepositoryMirroringController/CreateMirror',
            repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryMirroringCreateMirrorRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryMirroringCreateMirrorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class GitMirrorRepositoryReadControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
                '/config.repositories.GitMirrorRepositoryReadController/List',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryListRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryListResponse.FromString,
                _registered_method=True)
        self.Retrieve = channel.unary_unary(
                '/config.repositories.GitMirrorRepositoryReadController/Retrieve',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryRetrieveRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryResponse.FromString,
                _registered_method=True)


class GitMirrorRepositoryReadControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GitMirrorRepositoryReadControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryListRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryListResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryRetrieveRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'config.repositories.GitMirrorRepositoryReadController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('config.repositories.GitMirrorRepositoryReadController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GitMirrorRepositoryReadController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.GitMirrorRepositoryReadController/List',
            repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryListRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.GitMirrorRepositoryReadController/Retrieve',
            repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryRetrieveRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class GitRepositoryAdminControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/config.repositories.GitRepositoryAdminController/Create',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryResponse.FromString,
                _registered_method=True)
        self.Destroy = channel.unary_unary(
                '/config.repositories.GitRepositoryAdminController/Destroy',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryDestroyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/config.repositories.GitRepositoryAdminController/List',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryListRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryListResponse.FromString,
                _registered_method=True)
        self.PartialUpdate = channel.unary_unary(
                '/config.repositories.GitRepositoryAdminController/PartialUpdate',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryPartialUpdateRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryResponse.FromString,
                _registered_method=True)
        self.Retrieve = channel.unary_unary(
                '/config.repositories.GitRepositoryAdminController/Retrieve',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryRetrieveRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/config.repositories.GitRepositoryAdminController/Update',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryResponse.FromString,
                _registered_method=True)


class GitRepositoryAdminControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PartialUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GitRepositoryAdminControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryResponse.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryDestroyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryListRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryListResponse.SerializeToString,
            ),
            'PartialUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.PartialUpdate,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryPartialUpdateRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryRetrieveRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'config.repositories.GitRepositoryAdminController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('config.repositories.GitRepositoryAdminController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GitRepositoryAdminController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.GitRepositoryAdminController/Create',
            repositories_dot_grpc_dot_repositories__pb2.GitRepositoryRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.GitRepositoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.GitRepositoryAdminController/Destroy',
            repositories_dot_grpc_dot_repositories__pb2.GitRepositoryDestroyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.GitRepositoryAdminController/List',
            repositories_dot_grpc_dot_repositories__pb2.GitRepositoryListRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.GitRepositoryListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PartialUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.GitRepositoryAdminController/PartialUpdate',
            repositories_dot_grpc_dot_repositories__pb2.GitRepositoryPartialUpdateRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.GitRepositoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.GitRepositoryAdminController/Retrieve',
            repositories_dot_grpc_dot_repositories__pb2.GitRepositoryRetrieveRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.GitRepositoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.GitRepositoryAdminController/Update',
            repositories_dot_grpc_dot_repositories__pb2.GitRepositoryRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.GitRepositoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class GitRepositoryCreationControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/config.repositories.GitRepositoryCreationController/Create',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryCreationCreateRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryCreationCreateResponse.FromString,
                _registered_method=True)


class GitRepositoryCreationControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GitRepositoryCreationControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryCreationCreateRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryCreationCreateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'config.repositories.GitRepositoryCreationController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('config.repositories.GitRepositoryCreationController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GitRepositoryCreationController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.GitRepositoryCreationController/Create',
            repositories_dot_grpc_dot_repositories__pb2.GitRepositoryCreationCreateRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.GitRepositoryCreationCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class GitRepositoryMigrationControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Migrate = channel.unary_unary(
                '/config.repositories.GitRepositoryMigrationController/Migrate',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryMigrationMigrateRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryMigrationMigrateResponse.FromString,
                _registered_method=True)
        self.MigrateFromExternal = channel.unary_unary(
                '/config.repositories.GitRepositoryMigrationController/MigrateFromExternal',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryMigrationMigrateFromExternalRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryMigrationMigrateFromExternalResponse.FromString,
                _registered_method=True)


class GitRepositoryMigrationControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Migrate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MigrateFromExternal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GitRepositoryMigrationControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Migrate': grpc.unary_unary_rpc_method_handler(
                    servicer.Migrate,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryMigrationMigrateRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryMigrationMigrateResponse.SerializeToString,
            ),
            'MigrateFromExternal': grpc.unary_unary_rpc_method_handler(
                    servicer.MigrateFromExternal,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryMigrationMigrateFromExternalRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryMigrationMigrateFromExternalResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'config.repositories.GitRepositoryMigrationController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('config.repositories.GitRepositoryMigrationController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GitRepositoryMigrationController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Migrate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.GitRepositoryMigrationController/Migrate',
            repositories_dot_grpc_dot_repositories__pb2.GitRepositoryMigrationMigrateRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.GitRepositoryMigrationMigrateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MigrateFromExternal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.GitRepositoryMigrationController/MigrateFromExternal',
            repositories_dot_grpc_dot_repositories__pb2.GitRepositoryMigrationMigrateFromExternalRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.GitRepositoryMigrationMigrateFromExternalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class GitRepositoryReadControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
                '/config.repositories.GitRepositoryReadController/List',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryListRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryListResponse.FromString,
                _registered_method=True)
        self.Retrieve = channel.unary_unary(
                '/config.repositories.GitRepositoryReadController/Retrieve',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryRetrieveRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryResponse.FromString,
                _registered_method=True)


class GitRepositoryReadControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GitRepositoryReadControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryListRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryListResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryRetrieveRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'config.repositories.GitRepositoryReadController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('config.repositories.GitRepositoryReadController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GitRepositoryReadController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.GitRepositoryReadController/List',
            repositories_dot_grpc_dot_repositories__pb2.GitRepositoryListRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.GitRepositoryListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.GitRepositoryReadController/Retrieve',
            repositories_dot_grpc_dot_repositories__pb2.GitRepositoryRetrieveRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.GitRepositoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class GitRepositorySyncControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SyncNow = channel.unary_unary(
                '/config.repositories.GitRepositorySyncController/SyncNow',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositorySyncSyncNowRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositorySyncSyncNowResponse.FromString,
                _registered_method=True)


class GitRepositorySyncControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SyncNow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GitRepositorySyncControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SyncNow': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncNow,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositorySyncSyncNowRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositorySyncSyncNowResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'config.repositories.GitRepositorySyncController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('config.repositories.GitRepositorySyncController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GitRepositorySyncController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SyncNow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.GitRepositorySyncController/SyncNow',
            repositories_dot_grpc_dot_repositories__pb2.GitRepositorySyncSyncNowRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.GitRepositorySyncSyncNowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SyncTaskAdminControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/config.repositories.SyncTaskAdminController/Create',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.SyncTaskRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.SyncTaskResponse.FromString,
                _registered_method=True)
        self.Destroy = channel.unary_unary(
                '/config.repositories.SyncTaskAdminController/Destroy',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.SyncTaskDestroyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/config.repositories.SyncTaskAdminController/List',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.SyncTaskListRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.SyncTaskListResponse.FromString,
                _registered_method=True)
        self.PartialUpdate = channel.unary_unary(
                '/config.repositories.SyncTaskAdminController/PartialUpdate',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.SyncTaskPartialUpdateRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.SyncTaskResponse.FromString,
                _registered_method=True)
        self.Retrieve = channel.unary_unary(
                '/config.repositories.SyncTaskAdminController/Retrieve',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.SyncTaskRetrieveRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.SyncTaskResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/config.repositories.SyncTaskAdminController/Update',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.SyncTaskRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.SyncTaskResponse.FromString,
                _registered_method=True)


class SyncTaskAdminControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PartialUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SyncTaskAdminControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.SyncTaskRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.SyncTaskResponse.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.SyncTaskDestroyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.SyncTaskListRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.SyncTaskListResponse.SerializeToString,
            ),
            'PartialUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.PartialUpdate,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.SyncTaskPartialUpdateRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.SyncTaskResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.SyncTaskRetrieveRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.SyncTaskResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.SyncTaskRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.SyncTaskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'config.repositories.SyncTaskAdminController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('config.repositories.SyncTaskAdminController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SyncTaskAdminController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.SyncTaskAdminController/Create',
            repositories_dot_grpc_dot_repositories__pb2.SyncTaskRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.SyncTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.SyncTaskAdminController/Destroy',
            repositories_dot_grpc_dot_repositories__pb2.SyncTaskDestroyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.SyncTaskAdminController/List',
            repositories_dot_grpc_dot_repositories__pb2.SyncTaskListRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.SyncTaskListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PartialUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.SyncTaskAdminController/PartialUpdate',
            repositories_dot_grpc_dot_repositories__pb2.SyncTaskPartialUpdateRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.SyncTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.SyncTaskAdminController/Retrieve',
            repositories_dot_grpc_dot_repositories__pb2.SyncTaskRetrieveRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.SyncTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.SyncTaskAdminController/Update',
            repositories_dot_grpc_dot_repositories__pb2.SyncTaskRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.SyncTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SyncTaskReadControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
                '/config.repositories.SyncTaskReadController/List',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.SyncTaskListRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.SyncTaskListResponse.FromString,
                _registered_method=True)
        self.Retrieve = channel.unary_unary(
                '/config.repositories.SyncTaskReadController/Retrieve',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.SyncTaskRetrieveRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.SyncTaskResponse.FromString,
                _registered_method=True)


class SyncTaskReadControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SyncTaskReadControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.SyncTaskListRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.SyncTaskListResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.SyncTaskRetrieveRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.SyncTaskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'config.repositories.SyncTaskReadController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('config.repositories.SyncTaskReadController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SyncTaskReadController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.SyncTaskReadController/List',
            repositories_dot_grpc_dot_repositories__pb2.SyncTaskListRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.SyncTaskListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.SyncTaskReadController/Retrieve',
            repositories_dot_grpc_dot_repositories__pb2.SyncTaskRetrieveRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.SyncTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TaskStatusControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRepositoryTasks = channel.unary_unary(
                '/config.repositories.TaskStatusController/GetRepositoryTasks',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.TaskStatusGetRepositoryTasksRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.TaskStatusGetRepositoryTasksResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/config.repositories.TaskStatusController/GetStatus',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.TaskStatusGetStatusRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.TaskStatusGetStatusResponse.FromString,
                _registered_method=True)


class TaskStatusControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRepositoryTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskStatusControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRepositoryTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRepositoryTasks,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.TaskStatusGetRepositoryTasksRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.TaskStatusGetRepositoryTasksResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.TaskStatusGetStatusRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.TaskStatusGetStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'config.repositories.TaskStatusController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('config.repositories.TaskStatusController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TaskStatusController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRepositoryTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.TaskStatusController/GetRepositoryTasks',
            repositories_dot_grpc_dot_repositories__pb2.TaskStatusGetRepositoryTasksRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.TaskStatusGetRepositoryTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.TaskStatusController/GetStatus',
            repositories_dot_grpc_dot_repositories__pb2.TaskStatusGetStatusRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.TaskStatusGetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
