# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from repositories.grpc import repositories_pb2 as repositories_dot_grpc_dot_repositories__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in repositories/grpc/repositories_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GitMirrorRepositoryControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/config.repositories.GitMirrorRepositoryController/Create',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryResponse.FromString,
                _registered_method=True)
        self.Destroy = channel.unary_unary(
                '/config.repositories.GitMirrorRepositoryController/Destroy',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryDestroyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/config.repositories.GitMirrorRepositoryController/List',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryListRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryListResponse.FromString,
                _registered_method=True)
        self.PartialUpdate = channel.unary_unary(
                '/config.repositories.GitMirrorRepositoryController/PartialUpdate',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryPartialUpdateRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryResponse.FromString,
                _registered_method=True)
        self.Retrieve = channel.unary_unary(
                '/config.repositories.GitMirrorRepositoryController/Retrieve',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryRetrieveRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/config.repositories.GitMirrorRepositoryController/Update',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryResponse.FromString,
                _registered_method=True)


class GitMirrorRepositoryControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PartialUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GitMirrorRepositoryControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryResponse.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryDestroyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryListRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryListResponse.SerializeToString,
            ),
            'PartialUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.PartialUpdate,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryPartialUpdateRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryRetrieveRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'config.repositories.GitMirrorRepositoryController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('config.repositories.GitMirrorRepositoryController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GitMirrorRepositoryController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.GitMirrorRepositoryController/Create',
            repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.GitMirrorRepositoryController/Destroy',
            repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryDestroyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.GitMirrorRepositoryController/List',
            repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryListRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PartialUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.GitMirrorRepositoryController/PartialUpdate',
            repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryPartialUpdateRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.GitMirrorRepositoryController/Retrieve',
            repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryRetrieveRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.GitMirrorRepositoryController/Update',
            repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.GitMirrorRepositoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class GitRepositoryControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/config.repositories.GitRepositoryController/Create',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryResponse.FromString,
                _registered_method=True)
        self.Destroy = channel.unary_unary(
                '/config.repositories.GitRepositoryController/Destroy',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryDestroyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/config.repositories.GitRepositoryController/List',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryListRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryListResponse.FromString,
                _registered_method=True)
        self.ListRefs = channel.unary_unary(
                '/config.repositories.GitRepositoryController/ListRefs',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryListRefsRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryListRefsResponse.FromString,
                _registered_method=True)
        self.ListTree = channel.unary_unary(
                '/config.repositories.GitRepositoryController/ListTree',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryListTreeRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.RepositoryTreeEntryListResponse.FromString,
                _registered_method=True)
        self.PartialUpdate = channel.unary_unary(
                '/config.repositories.GitRepositoryController/PartialUpdate',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryPartialUpdateRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryResponse.FromString,
                _registered_method=True)
        self.Retrieve = channel.unary_unary(
                '/config.repositories.GitRepositoryController/Retrieve',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryRetrieveRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/config.repositories.GitRepositoryController/Update',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryResponse.FromString,
                _registered_method=True)


class GitRepositoryControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRefs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTree(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PartialUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GitRepositoryControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryResponse.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryDestroyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryListRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryListResponse.SerializeToString,
            ),
            'ListRefs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRefs,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryListRefsRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryListRefsResponse.SerializeToString,
            ),
            'ListTree': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTree,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryListTreeRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.RepositoryTreeEntryListResponse.SerializeToString,
            ),
            'PartialUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.PartialUpdate,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryPartialUpdateRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryRetrieveRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.GitRepositoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'config.repositories.GitRepositoryController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('config.repositories.GitRepositoryController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GitRepositoryController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.GitRepositoryController/Create',
            repositories_dot_grpc_dot_repositories__pb2.GitRepositoryRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.GitRepositoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.GitRepositoryController/Destroy',
            repositories_dot_grpc_dot_repositories__pb2.GitRepositoryDestroyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.GitRepositoryController/List',
            repositories_dot_grpc_dot_repositories__pb2.GitRepositoryListRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.GitRepositoryListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRefs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.GitRepositoryController/ListRefs',
            repositories_dot_grpc_dot_repositories__pb2.GitRepositoryListRefsRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.GitRepositoryListRefsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.GitRepositoryController/ListTree',
            repositories_dot_grpc_dot_repositories__pb2.GitRepositoryListTreeRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.RepositoryTreeEntryListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PartialUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.GitRepositoryController/PartialUpdate',
            repositories_dot_grpc_dot_repositories__pb2.GitRepositoryPartialUpdateRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.GitRepositoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.GitRepositoryController/Retrieve',
            repositories_dot_grpc_dot_repositories__pb2.GitRepositoryRetrieveRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.GitRepositoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.GitRepositoryController/Update',
            repositories_dot_grpc_dot_repositories__pb2.GitRepositoryRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.GitRepositoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MirrorRepositoryControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateMirror = channel.unary_unary(
                '/config.repositories.MirrorRepositoryController/CreateMirror',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.MirrorRepositoryCreateMirrorRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.MirrorRepositoryCreateMirrorResponse.FromString,
                _registered_method=True)
        self.SyncNow = channel.unary_unary(
                '/config.repositories.MirrorRepositoryController/SyncNow',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.MirrorRepositorySyncNowRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.MirrorRepositorySyncNowResponse.FromString,
                _registered_method=True)


class MirrorRepositoryControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateMirror(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncNow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MirrorRepositoryControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateMirror': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMirror,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.MirrorRepositoryCreateMirrorRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.MirrorRepositoryCreateMirrorResponse.SerializeToString,
            ),
            'SyncNow': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncNow,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.MirrorRepositorySyncNowRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.MirrorRepositorySyncNowResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'config.repositories.MirrorRepositoryController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('config.repositories.MirrorRepositoryController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MirrorRepositoryController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateMirror(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.MirrorRepositoryController/CreateMirror',
            repositories_dot_grpc_dot_repositories__pb2.MirrorRepositoryCreateMirrorRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.MirrorRepositoryCreateMirrorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncNow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.MirrorRepositoryController/SyncNow',
            repositories_dot_grpc_dot_repositories__pb2.MirrorRepositorySyncNowRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.MirrorRepositorySyncNowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RepositoryCreationControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/config.repositories.RepositoryCreationController/Create',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.RepositoryCreationCreateRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.RepositoryCreationCreateResponse.FromString,
                _registered_method=True)
        self.Migrate = channel.unary_unary(
                '/config.repositories.RepositoryCreationController/Migrate',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.RepositoryCreationMigrateRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.RepositoryCreationMigrateResponse.FromString,
                _registered_method=True)
        self.MigrateFromExternal = channel.unary_unary(
                '/config.repositories.RepositoryCreationController/MigrateFromExternal',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.RepositoryCreationMigrateFromExternalRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.RepositoryCreationMigrateFromExternalResponse.FromString,
                _registered_method=True)


class RepositoryCreationControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Migrate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MigrateFromExternal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RepositoryCreationControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.RepositoryCreationCreateRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.RepositoryCreationCreateResponse.SerializeToString,
            ),
            'Migrate': grpc.unary_unary_rpc_method_handler(
                    servicer.Migrate,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.RepositoryCreationMigrateRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.RepositoryCreationMigrateResponse.SerializeToString,
            ),
            'MigrateFromExternal': grpc.unary_unary_rpc_method_handler(
                    servicer.MigrateFromExternal,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.RepositoryCreationMigrateFromExternalRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.RepositoryCreationMigrateFromExternalResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'config.repositories.RepositoryCreationController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('config.repositories.RepositoryCreationController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RepositoryCreationController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.RepositoryCreationController/Create',
            repositories_dot_grpc_dot_repositories__pb2.RepositoryCreationCreateRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.RepositoryCreationCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Migrate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.RepositoryCreationController/Migrate',
            repositories_dot_grpc_dot_repositories__pb2.RepositoryCreationMigrateRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.RepositoryCreationMigrateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MigrateFromExternal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.RepositoryCreationController/MigrateFromExternal',
            repositories_dot_grpc_dot_repositories__pb2.RepositoryCreationMigrateFromExternalRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.RepositoryCreationMigrateFromExternalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SyncTaskControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
                '/config.repositories.SyncTaskController/List',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.SyncTaskListRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.SyncTaskListResponse.FromString,
                _registered_method=True)
        self.Retrieve = channel.unary_unary(
                '/config.repositories.SyncTaskController/Retrieve',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.SyncTaskRetrieveRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.SyncTaskResponse.FromString,
                _registered_method=True)


class SyncTaskControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SyncTaskControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.SyncTaskListRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.SyncTaskListResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.SyncTaskRetrieveRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.SyncTaskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'config.repositories.SyncTaskController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('config.repositories.SyncTaskController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SyncTaskController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.SyncTaskController/List',
            repositories_dot_grpc_dot_repositories__pb2.SyncTaskListRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.SyncTaskListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.SyncTaskController/Retrieve',
            repositories_dot_grpc_dot_repositories__pb2.SyncTaskRetrieveRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.SyncTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TaskStatusControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRepositoryTasks = channel.unary_unary(
                '/config.repositories.TaskStatusController/GetRepositoryTasks',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.TaskStatusGetRepositoryTasksRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.TaskStatusGetRepositoryTasksResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/config.repositories.TaskStatusController/GetStatus',
                request_serializer=repositories_dot_grpc_dot_repositories__pb2.TaskStatusGetStatusRequest.SerializeToString,
                response_deserializer=repositories_dot_grpc_dot_repositories__pb2.TaskStatusGetStatusResponse.FromString,
                _registered_method=True)


class TaskStatusControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRepositoryTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskStatusControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRepositoryTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRepositoryTasks,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.TaskStatusGetRepositoryTasksRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.TaskStatusGetRepositoryTasksResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=repositories_dot_grpc_dot_repositories__pb2.TaskStatusGetStatusRequest.FromString,
                    response_serializer=repositories_dot_grpc_dot_repositories__pb2.TaskStatusGetStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'config.repositories.TaskStatusController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('config.repositories.TaskStatusController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TaskStatusController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRepositoryTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.TaskStatusController/GetRepositoryTasks',
            repositories_dot_grpc_dot_repositories__pb2.TaskStatusGetRepositoryTasksRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.TaskStatusGetRepositoryTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.repositories.TaskStatusController/GetStatus',
            repositories_dot_grpc_dot_repositories__pb2.TaskStatusGetStatusRequest.SerializeToString,
            repositories_dot_grpc_dot_repositories__pb2.TaskStatusGetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
