# Generated by Django 4.2.27 on 2025-12-20 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='accounts.organisation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='organisationinvite',
            name='role',
            field=models.CharField(choices=[('none', 'None'), ('read', 'Read'), ('write', 'Write'), ('admin', 'Admin')], default='read', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('none', 'None'), ('read', 'Read'), ('write', 'Write'), ('admin', 'Admin')], default='read', max_length=20),
        ),
        migrations.CreateModel(
            name='OrganisationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('none', 'None'), ('read', 'Read'), ('write', 'Write'), ('admin', 'Admin')], default='read', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('maintainer', 'Maintainer')], default='member', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['team__name'],
                'indexes': [models.Index(fields=['team', 'user', 'is_active'], name='accounts_te_team_id_779367_idx'), models.Index(fields=['user'], name='accounts_te_user_id_f0e54d_idx')],
                'unique_together': {('team', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['organisation', 'slug'], name='accounts_te_organis_1264bd_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['organisation', 'is_active'], name='accounts_te_organis_fa2a41_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('organisation', 'slug')},
        ),
        migrations.AddIndex(
            model_name='organisationmembership',
            index=models.Index(fields=['organisation', 'role'], name='accounts_or_organis_521994_idx'),
        ),
        migrations.AddIndex(
            model_name='organisationmembership',
            index=models.Index(fields=['user', 'organisation', 'is_active'], name='accounts_or_user_id_726f3c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organisationmembership',
            unique_together={('user', 'organisation')},
        ),
    ]
