# Generated by Django 4.2.27 on 2026-01-16 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0003_repositoryaccesspolicy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Branch, tag, or commit hash', max_length=255)),
                ('workdir', models.CharField(help_text='Path to the working directory in the repository', max_length=255)),
                ('conf_path', models.CharField(help_text='Path to the configuration file in the repository', max_length=255)),
                ('last_build_at', models.DateTimeField(auto_now=True)),
                ('global_context', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-last_build_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('content_hash', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('jsx_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='repositories.gitrepository')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_page_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='documents.build')),
            ],
            options={
                'ordering': ['current_page_name'],
                'unique_together': {('document', 'current_page_name')},
            },
        ),
        migrations.AddField(
            model_name='build',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='documents.document'),
        ),
        migrations.CreateModel(
            name='StaticAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('hash', models.CharField(max_length=40)),
                ('file', models.FileField(upload_to='static_assets/')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_assets', to='documents.document')),
            ],
            options={
                'unique_together': {('document', 'path')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sphinx_id', models.CharField(max_length=255)),
                ('hash', models.CharField(max_length=40)),
                ('source_path', models.CharField(max_length=255)),
                ('start_line', models.IntegerField()),
                ('end_line', models.IntegerField()),
                ('content_block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='documents.contentblock')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='documents.page')),
            ],
            options={
                'unique_together': {('page', 'hash')},
            },
        ),
    ]
