# Generated by Django 4.2.27 on 2026-01-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['path']},
        ),
        migrations.RenameField(
            model_name='page',
            old_name='document',
            new_name='build',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='current_page_name',
            new_name='path',
        ),
        migrations.AddField(
            model_name='build',
            name='commit_hash',
            field=models.CharField(blank=True, help_text='Commit hash of the build', max_length=40),
        ),
        migrations.AddField(
            model_name='build',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='build',
            name='version',
            field=models.CharField(blank=True, help_text='Version number generated by dunamai', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('build', 'path')},
        ),
    ]
