from django.db import models
from django.contrib.auth.models import User


class Document(models.Model):
    title = models.CharField(max_length=255)
    
    source = models.ForeignKey('repositories.GitRepository', on_delete=models.CASCADE, related_name='documents')

    class Meta:
        ordering = ['title']

    def __str__(self) -> str:
        return self.title


class Build(models.Model):
    document = models.ForeignKey(Document, on_delete=models.CASCADE, related_name='builds')

    reference = models.CharField(max_length=255, help_text="Branch, tag, or commit hash")
    
    language = models.CharField(max_length=10, default='en')
    
    commit_hash = models.CharField(max_length=40, blank=True, help_text="Commit hash of the build")
    
    version = models.CharField(max_length=255, blank=True, help_text="Version number generated by dunamai")

    workdir = models.CharField(max_length=255, help_text="Path to the working directory in the repository")

    conf_path = models.CharField(max_length=255, help_text="Path to the configuration file in the repository")

    last_build_at = models.DateTimeField(auto_now=True)

    global_context = models.JSONField(default=dict, blank=True)

    class Meta:
        ordering = ['-last_build_at']

    def __str__(self) -> str:
        return f"{self.document.title} - {self.reference}"
    
class Page(models.Model):
    build = models.ForeignKey(Build, on_delete=models.CASCADE, related_name='pages')
    
    path = models.CharField(max_length=255)

    title = models.CharField(max_length=255)

    jsx_content = models.TextField()
    
    context = models.JSONField(default=dict, blank=True)
        
    class Meta:
        unique_together = ('build', 'path')
        ordering = ['path']

    def __str__(self) -> str:
        return f"{self.build.document.title} - {self.path}"
    
class Section(models.Model):
    page = models.ForeignKey(Page, on_delete=models.CASCADE, related_name='sections')
    
    title = models.CharField(max_length=255)

    sphinx_id = models.CharField(max_length=255)

    hash = models.CharField(max_length=40)

    source_path = models.CharField(max_length=255)

    start_line = models.IntegerField()

    end_line = models.IntegerField()

    content_block = models.ForeignKey(
            'ContentBlock', 
            on_delete=models.PROTECT, 
            related_name='sections'
        )    
    class Meta:
        unique_together = ('page', 'hash')

    def __str__(self) -> str:
        return f"{self.page.path} - {self.title}"
    
class ContentBlock(models.Model):
    """
    Stores unique content blocks identified by their hash.
    Primary key is the hash itself for efficient lookups and storage.
    """
    content_hash = models.CharField(max_length=40, primary_key=True)

    jsx_content = models.TextField()

    def __str__(self) -> str:
        return self.content_hash


class StaticAsset(models.Model):
    document = models.ForeignKey(Document, on_delete=models.CASCADE, related_name='static_assets')
    
    path = models.CharField(max_length=255)

    hash = models.CharField(max_length=40)

    file = models.FileField(upload_to='static_assets/')

    class Meta:
        unique_together = ('document', 'path')

    def __str__(self) -> str:
        return f"{self.document.title} - {self.path}"